# -------------------------------------------------------------------------------------------------
bp:
	@ python3 -O Bipartite.py

bp_d:
	@ python3 Bipartite.py debug

clean_bp:
	@ sudo rm -r Bipartite/out/* 2>/dev/null || true
# -------------------------------------------------------------------------------------------------
bp2:
	@ python3 -O Bipartite2.py

bp2_d:
	@ python3 Bipartite2.py
# -------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------
bpl:
	@ python3 -O BipartiteLindblad.py

bpl_d:
	@ python3 BipartiteLindblad.py debug

clean_bpl:
	@ sudo rm -r BipartiteLindblad/out/* 2>/dev/null || true
# -------------------------------------------------------------------------------------------------

# -------------------------------------------------------------------------------------------------
bpg:
	@ python3 -O BipartiteGeneral.py

bpg_d:
	@ python3 BipartiteGeneral.py debug

clean_bpg:
	@ sudo rm -r BipartiteGeneral/out/* 2>/dev/null || true
# -------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------
bpgl:
	@ python3 -O BipartiteGeneralLindblad.py

bpgl_d:
	@ python3 BipartiteGeneralLindblad.py debug

clean_bpgl:
	@ sudo rm -r BipartiteGeneralLindblad/out/* 2>/dev/null || true
# -------------------------------------------------------------------------------------------------

# -------------------------------------------------------------------------------------------------
bpg2:
	@ python3 -O Bipartite2General.py

bpg2_d:
	@ python3 Bipartite2General.py debug

clean_bpg2:
	@ sudo rm -r Bipartite2General/out/* 2>/dev/null || true
# -------------------------------------------------------------------------------------------------
